"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { api, formatNumber } from "@/lib/api";
import type { AccountMetric, Platform, SocialAccount } from "@/lib/types";

export default function AccountsPage() {
  const [platforms,setPlatforms]=useState<Platform[]>([]); const [accounts,setAccounts]=useState<SocialAccount[]>([]); const [metrics,setMetrics]=useState<AccountMetric[]>([]);
  const [platformId,setPlatformId]=useState(""); const [name,setName]=useState(""); const [handle,setHandle]=useState(""); const [externalId,setExternalId]=useState(""); const [profileUrl,setProfileUrl]=useState("");
  const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [syncing,setSyncing]=useState("");
  async function load(){const [p,a,m]=await Promise.all([api<Platform[]>("/platforms"),api<SocialAccount[]>("/accounts"),api<AccountMetric[]>("/accounts/metrics/latest")]);setPlatforms(p);setAccounts(a);setMetrics(m);if(!platformId&&p[0])setPlatformId(p[0].id)}
  useEffect(()=>{load().catch(e=>setError(e.message))},[]);
  const pmap=useMemo(()=>new Map(platforms.map(p=>[p.id,p])),[platforms]); const mmap=useMemo(()=>new Map(metrics.map(m=>[m.account_id,m])),[metrics]);
  async function submit(e:FormEvent){e.preventDefault();setError("");await api<SocialAccount>("/accounts",{method:"POST",body:JSON.stringify({platform_id:platformId,name,handle:handle||null,external_id:externalId||null,profile_url:profileUrl||null})}).then(()=>{setName("");setHandle("");setExternalId("");setProfileUrl("");setNotice("账号已添加");return load()}).catch(e=>setError(e.message))}
  async function sync(a:SocialAccount){setSyncing(a.id);setError("");setNotice("");try{await api<AccountMetric>(`/accounts/${a.id}/sync`,{method:"POST"});setNotice(`${a.name} 数据已同步`);await load()}catch(e){setError(e instanceof Error?e.message:"同步失败")}finally{setSyncing("")}}
  async function remove(a:SocialAccount){if(!confirm(`确定删除账号“${a.name}”以及该账号下保存的内容和快照吗？`))return;await api<void>(`/accounts/${a.id}`,{method:"DELETE"});await load()}
  return <><header className="pageHeader"><div><div className="eyebrow">Accounts</div><h1>账号管理</h1><p>每个平台可以添加多个独立账号；API 授权也将按账号隔离。</p></div></header>{notice?<div className="notice">{notice}</div>:null}{error?<div className="error">{error}</div>:null}
  <section className="card"><div className="sectionTitle"><h2>添加账号</h2><span>独立保存</span></div><form className="form" onSubmit={submit}><div className="field"><label>平台</label><select className="select" value={platformId} onChange={e=>setPlatformId(e.target.value)}>{platforms.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="field"><label>账号名称</label><input className="input" required value={name} onChange={e=>setName(e.target.value)} placeholder="例如 ZenoMinerals Main" /></div><div className="field"><label>Handle / 用户名</label><input className="input" value={handle} onChange={e=>setHandle(e.target.value)} placeholder="@username" /></div><div className="field"><label>平台内部 ID</label><input className="input" value={externalId} onChange={e=>setExternalId(e.target.value)} placeholder="YouTube 可先填 Channel ID" /></div><div className="field full"><label>主页链接</label><input className="input" type="url" value={profileUrl} onChange={e=>setProfileUrl(e.target.value)} placeholder="https://..." /></div><div><button className="button" type="submit">保存账号</button></div></form></section>
  <section className="section"><div className="sectionTitle"><h2>已保存账号</h2><span>{accounts.length}</span></div>{accounts.length===0?<div className="empty">暂无账号</div>:<div className="dataList">{accounts.map(a=>{const m=mmap.get(a.id);const p=pmap.get(a.platform_id);return <div className="row" key={a.id}><div><div className="rowTitle">{a.name} <span className="pill">{p?.name}</span></div><div className="rowMeta">{a.handle||"无 handle"} · {m?`${formatNumber(m.followers)} followers · ${formatNumber(m.views)} views`:`尚无数据快照`}</div></div><div style={{display:"flex",gap:7}}><button className="button secondary" onClick={()=>sync(a)} disabled={syncing===a.id}>{syncing===a.id?"同步中…":"同步数据"}</button><button className="button danger" onClick={()=>remove(a)}>删除</button></div></div>})}</div>}</section></>;
}
