"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { api, formatNumber } from "@/lib/api";
import type { ContentMetric, PublishedContent, SocialAccount } from "@/lib/types";

export default function ContentPage(){const [accounts,setAccounts]=useState<SocialAccount[]>([]);const [items,setItems]=useState<PublishedContent[]>([]);const [metrics,setMetrics]=useState<ContentMetric[]>([]);const [accountId,setAccountId]=useState("");const [title,setTitle]=useState("");const [url,setUrl]=useState("");const [externalId,setExternalId]=useState("");const [type,setType]=useState("video");const [error,setError]=useState("");
async function load(){const[a,c,m]=await Promise.all([api<SocialAccount[]>("/accounts"),api<PublishedContent[]>("/content"),api<ContentMetric[]>("/content/metrics/latest")]);setAccounts(a);setItems(c);setMetrics(m);if(!accountId&&a[0])setAccountId(a[0].id)}useEffect(()=>{load().catch(e=>setError(e.message))},[]);const amap=useMemo(()=>new Map(accounts.map(a=>[a.id,a])),[accounts]);const mmap=useMemo(()=>new Map(metrics.map(m=>[m.content_id,m])),[metrics]);async function submit(e:FormEvent){e.preventDefault();await api<PublishedContent>("/content",{method:"POST",body:JSON.stringify({account_id:accountId,title,content_type:type,external_id:externalId||null,url:url||null,published_at:new Date().toISOString()})});setTitle("");setUrl("");setExternalId("");await load()}async function remove(id:string){if(!confirm("确定删除这条内容和所有历史数据吗？"))return;await api<void>(`/content/${id}`,{method:"DELETE"});await load()}
return <><header className="pageHeader"><div><div className="eyebrow">Published Content</div><h1>内容数据</h1><p>记录四个平台的单条视频、Reel、Post 或 Pin，并保存后续数据快照。</p></div></header>{error?<div className="error">{error}</div>:null}<section className="card"><div className="sectionTitle"><h2>添加已发布内容</h2><span>Publication record</span></div><form className="form" onSubmit={submit}><div className="field"><label>账号</label><select className="select" required value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">选择账号</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div><div className="field"><label>内容类型</label><select className="select" value={type} onChange={e=>setType(e.target.value)}><option value="video">Video</option><option value="short">Short / Reel</option><option value="post">Post</option><option value="pin">Pin</option></select></div><div className="field full"><label>标题</label><input className="input" required value={title} onChange={e=>setTitle(e.target.value)} /></div><div className="field"><label>作品链接</label><input className="input" type="url" value={url} onChange={e=>setUrl(e.target.value)} /></div><div className="field"><label>平台内容 ID</label><input className="input" value={externalId} onChange={e=>setExternalId(e.target.value)} /></div><div><button className="button">保存内容</button></div></form></section><section className="section"><div className="sectionTitle"><h2>内容列表</h2><span>{items.length}</span></div>{items.length===0?<div className="empty">还没有发布内容记录</div>:<div className="dataList">{items.map(item=>{const m=mmap.get(item.id);return <div className="row" key={item.id}><div><div className="rowTitle">{item.title}</div><div className="rowMeta">{amap.get(item.account_id)?.name} · {item.content_type} · {m?`${formatNumber(m.views)} views · ${formatNumber(m.likes)} likes · ${formatNumber(m.comments)} comments`:`未记录数据`}</div></div><div style={{display:"flex",gap:7}}>{item.url?<a className="button secondary" href={item.url} target="_blank" rel="noreferrer">打开作品</a>:null}<button className="button danger" onClick={()=>remove(item.id)}>删除</button></div></div>})}</div>}</section></>}
